repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-symlinks
    -   id: check-yaml
    -   id: debug-statements
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8
