#!/usr/bin/env python3

import os
from pathlib import Path
import argparse

from striprtf.striprtf import rtf_to_text

parser = argparse.ArgumentParser(
    formatter_class=argparse.ArgumentDefaultsHelpFormatter
)

parser.add_argument('--src', help='Source location')
parser.add_argument('--dest', help='Destination location')

args = parser.parse_args()

src = str(Path(args.src).expanduser())
dest = str(Path(args.dest).expanduser())

sub_dirs = [f.path for f in os.scandir(src) if f.is_dir()]

for d in sub_dirs:
    output_file_name = d.split('/')[-1] \
        .lower() \
        .replace(' ', '') \
        .replace('.rtfd', '.txt')

    print(f'Converting {output_file_name}')

    with open(d + '/TXT.rtf') as f:
        rtf = f.read()
        text = rtf_to_text(rtf)

    with open(dest + f'/{output_file_name}', 'w') as f:
        f.write(text)
        print(f'Successfully converted {output_file_name}')
